-- Remove incorrect references to Sam Graham
CREATE OR REPLACE TABLE raw.player_stats AS
SELECT 
    player_id,
  CASE 
    WHEN name = 'Sam Grahamslaw' AND team = 'Northampton' THEN 'Sam Graham'
    ELSE name 
  END AS name,
    player_name,
    team,
    team_id,
    team_vs,
    team_vs_id,
    position,
    match_id,
    game_date,
    competition,
    competition_id,
    weight_kg,
    height_cm,
    carries,
    carries_per_minute,
    metres_carried,
    meters_run,
    runs,
    line_breaks,
    clean_breaks,
    defenders_beaten,
    offloads,
    offload,
    passes,
    try_assists,
    tries,
    points,
    kicks,
    kicks_from_hand,
    kick_percent_success,
    conversion_goals,
    penalty_goals,
    drop_goals_converted,
    tackles_made,
    tackles_completed,
    tackles_missed,
    missed_tackles,
    dominant_tackles,
    total_tackles_per_minute,
    tackles,
    lineouts_won,
    lineout_won_steal,
    total_lineouts,
    mauls_won,
    rucks_won,
    ruck_turnovers,
    turnovers_won,
    turnovers_lost,
    turnovers_conceded,
    turnover_knock_on,
    penalties_conceded,
    total_free_kicks_conceded,
    red_cards,
    yellow_cards,
    want_team,
    want_teamvs
from raw.player_stats